#' Remove autogenerated package Rd from man directory
#'
#' utils::package.skeleton() and roxygen2::roxygenize() leave us with an invalid
#' PACKAGENAME-package.Rd file in the man directory. It needs to be removed.
#'
#' @author Dominik Cullmann, <dominik.cullmann@@forst.bwl.de>
#' @section Version: $Id: 3d72fa8d41ea4e2e7b29ffdfefc45e58fe5274b5 $
#' @param package_directory Path to the directory.
#' @return value of \code{link{base::file.remove()}}.
remove_package_Rd <- function(package_directory) {
    package_name <- basename(package_directory)
    package_rd <- paste(package_name, '-package.Rd', sep = '')
    status <- file.remove(file.path(package_directory, 'man', package_rd))
    return(invisible(status))
}

#' Change License in the DESCRIPTION file to 'GPL'
#'
#' utils::package.skeleton() leaves us with a DESCRIPTION that throws a warning 
#' in R CMD check. Fix that.
#'
#' @author Dominik Cullmann, <dominik.cullmann@@forst.bwl.de>
#' @section Version: $Id: 3d72fa8d41ea4e2e7b29ffdfefc45e58fe5274b5 $
#' @param package_directory Path to the directory.
#' @return value of \code{link{writeLines}}.
clean_description <- function(package_directory) {
    description_file <- file.path(package_directory, 'DESCRIPTION') 
    description <-  readLines(description_file)
    description <-  sub('(License: ).*', '\\1GPL', description)
    status <- writeLines(description, con = description_file)
    return(invisible(status))
}

#' fix a \code{\link{package.skeleton}}s package skeleton. 
#'
#' This is just a conviniece wrapper to \code{\link{remove_package_Rd}} and
#' \code{\link{clean_description}}.
#'
#' @author Dominik Cullmann, <dominik.cullmann@@forst.bwl.de>
#' @section Version: $Id: 3d72fa8d41ea4e2e7b29ffdfefc45e58fe5274b5 $
#' @param package_directory Path to the directory.
#' @return invisibly NULL.
fix_package_documentation <- function(package_directory) {
    remove_package_Rd(package_directory)
    clean_description(package_directory)
    return(invisible(NULL))
}

#' build and check a temporary package intended for documentation mainly.
#'
#' We might want to see if the temporary package we've created to document our
#' code file would build and pass R CMD check as a proper package.
#' 
#' @author Dominik Cullmann, <dominik.cullmann@@forst.bwl.de>
#' @section Version: $Id: 3d72fa8d41ea4e2e7b29ffdfefc45e58fe5274b5 $
#' @param package_directory Path to the packages' directory.
#' @param working_directory Path to a working directory.
#' @param copy_tmp_files_to Path to copy temporary files from R CMD CHECK to.
#' @return invisibly 0, if R CMD check returned 0, nothing otherwise.
build_and_check_package <- function(package_directory, working_directory,
                                    copy_tmp_files_to) {
    on.exit(setwd(old_working_directory))
    # change to the template directory: we don't want to write to disk without
    # knowing where we are.
    old_working_directory <- setwd(working_directory)

    system(paste('R CMD build', package_directory))
    list.files(working_directory)
    package_name <- basename(package_directory)
    tar_ball <- list.files(pattern = paste(package_name, '.*tar.gz$', 
                                           sep = ''))
    r_cmd_check_status <- system(paste('R CMD check ', tar_ball))
    if (! is.null(copy_tmp_files_to)) {
        ## copy temporary files to see what R CMD check output was
        if(! file.exists(copy_tmp_files_to)) dir.create(copy_tmp_files_to)
        file.copy(working_directory, copy_tmp_files_to, overwrite = TRUE,
                  recursive = TRUE
                  )
    } else {
        if(r_cmd_check_status != 0) {
            message('You may want to set copy_tmp_files_to and rerun.')
        }
    }
    if(r_cmd_check_status != 0) {
        stop('R CMD check failed. Fix your sources.')
    }
    return(invisible(r_cmd_check_status))
}


